"""the bank: 12 dictionaries nested in a list"""

question_data = [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The HTML5 standard was published in 2014.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Coca-Cola&#039;s original colour was green.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                       "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
     "question": "The animated film &quot;Spirited Away&quot; won the Academy Award for Best Animated Feature at the 75th Academy Awards in 2003.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; takes place on Shadow Moses Island.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "MacOS is based on Linux.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Art", "type": "boolean", "difficulty": "medium",
     "question": "Pablo Picasso is one of the founding fathers of &quot;Cubism.&quot;", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                       "question": "AMD created the first consumer 64-bit processor.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "medium",
     "question": "The average lifespan of a wildcat is only around 5-6 years. ", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                      "question": "Albert Einstein had trouble with mathematics when he was in school.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Politics", "type": "boolean", "difficulty": "medium",
                                      "question": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "Bob Ross was a US Air Force pilot.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Star Trek&quot;, Klingons respect William Shakespeare, they even suspect him having a Klingon lineage.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Star Trek&quot;, Klingons are commonly referred to as &quot;Black Elves&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Politics", "type": "boolean", "difficulty": "medium",
     "question": "Helen Clark was the 37th Prime Minister of Australia.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;League of Legends&quot;, there exists four different types of Dragon.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "Sound can travel through a vacuum.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "The Korean War ended in 1953 without any ceasefire.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "medium",
                                      "question": "Sir Issac Newton served as a Member of Parliament, but the only recorded time he spoke was to complain about a draft in the chambers.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "Franz Joseph I was the last emperor of Austria.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Resident Evil&quot;, only Chris has access to the grenade launcher.",
     "correct_answer": "False", "incorrect_answers": ["True"]}]
